LIBWIPI_ROOT ?= ../..

APP_AID := libwipi-media-suite
APP_NAME := libwipi media suite
APP_SOURCES := main.c
APP_RESOURCES := assets/clip-data.bin=res/clip-data.bin
INSTALL_PROFILE ?= aram-raptor

include $(LIBWIPI_ROOT)/mk/application.mk
