LIBWIPI_ROOT ?= ../..

APP_AID := libwipi-memory-resource
APP_NAME := libwipi memory and resource
APP_SOURCES := main.c
APP_RESOURCES := assets/sdk-message.txt=res/sdk-message.txt

include $(LIBWIPI_ROOT)/mk/application.mk
