#!/usr/bin/env python3
"""Generate WIPI public headers, ABI veneers, and coverage documentation."""

from __future__ import annotations

import argparse
from collections import Counter
import csv
import json
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
VERSION_MANIFEST = ROOT / "spec" / "versions.json"
PROFILE_DIR = ROOT / "spec" / "profiles"
INSTALL_DIR = ROOT / "spec" / "install"

FAMILY_FILES = {
    "MC_SRL": "serial",
    "MC_GRP": "graphics",
    "MC_FS": "filesystem",
    "MC_NET": "network",
    "MC_HTTP": "http",
    "MC_UTIL": "utility",
    "MC_MDA": "media",
    "MC_MISC": "misc",
    "MC_PHN": "phone",
    "MC_DB": "database",
    "MC_KNL": "kernel",
    "MC_UIC": "uic",
}

GENERATED_NOTICE = "/* Generated by tools/generate.py. Do not edit. */\n"


def api_macro(api_level: str) -> str:
    token = re.sub(r"[^0-9A-Za-z]+", "_", api_level).strip("_")
    return f"LIBWIPI_API_LEVEL_{token}"


def read_version_manifest() -> tuple[dict[str, object], list[dict[str, object]]]:
    manifest = json.loads(VERSION_MANIFEST.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != 1:
        raise ValueError("unsupported version manifest schema")
    levels = manifest.get("levels")
    if not isinstance(levels, list) or not levels:
        raise ValueError("version manifest must contain API levels")
    names = [entry.get("api_level") for entry in levels]
    if any(not isinstance(name, str) or not name for name in names):
        raise ValueError("every API level must have a non-empty name")
    if len(set(names)) != len(names):
        raise ValueError("API levels must be unique")
    bootstrap = manifest.get("bootstrap_api_level")
    if bootstrap not in names:
        raise ValueError("bootstrap API level is not listed")
    return manifest, levels


def read_build_metadata() -> tuple[
    list[dict[str, object]],
    list[dict[str, object]],
    list[dict[str, object]],
]:
    _, levels = read_version_manifest()
    names = [str(entry["api_level"]) for entry in levels]

    profiles: list[dict[str, object]] = []
    for path in sorted(PROFILE_DIR.glob("*.json")):
        profile = json.loads(path.read_text(encoding="utf-8"))
        if profile.get("id") != path.stem:
            raise ValueError(f"profile id does not match {path.name}")
        mappings = profile.get("api_level_mappings")
        if not isinstance(mappings, dict) or not mappings:
            raise ValueError(f"profile {path.stem} has no API-level mappings")
        unknown = set(mappings).difference(names)
        if unknown:
            raise ValueError(
                f"profile {path.stem} maps unknown API levels: {sorted(unknown)}"
            )
        profiles.append(profile)

    install_profiles: list[dict[str, object]] = []
    profile_names = {str(profile["id"]) for profile in profiles}
    for path in sorted(INSTALL_DIR.glob("*.json")):
        install = json.loads(path.read_text(encoding="utf-8"))
        if install.get("id") != path.stem:
            raise ValueError(f"install profile id does not match {path.name}")
        if install.get("api_level") not in names:
            raise ValueError(
                f"install profile {path.stem} selects an unknown API level"
            )
        if install.get("abi_profile") not in profile_names:
            raise ValueError(
                f"install profile {path.stem} selects an unknown ABI profile"
            )
        install_profiles.append(install)

    implemented = {
        entry["api_level"]
        for entry in levels
        if entry.get("catalog_status") == "implemented"
    }
    for profile in profiles:
        for level, mapping in profile["api_level_mappings"].items():
            if mapping.get("target_build") and level not in implemented:
                raise ValueError(
                    f"profile {profile['id']} enables unimplemented API level {level}"
                )
            install_ids = mapping.get("install_profiles", [])
            if mapping.get("target_build") and not install_ids:
                raise ValueError(
                    f"profile {profile['id']} has no install profile for {level}"
                )
            known_install_ids = {"none"} | {
                str(install["id"]) for install in install_profiles
            }
            unknown_installs = set(install_ids).difference(known_install_ids)
            if unknown_installs:
                raise ValueError(
                    f"profile {profile['id']} maps unknown install profiles: "
                    f"{sorted(unknown_installs)}"
                )

    for install in install_profiles:
        profile = next(
            item for item in profiles if item["id"] == install["abi_profile"]
        )
        mapping = profile["api_level_mappings"].get(install["api_level"])
        if (
            not install.get("target_build")
            or not mapping
            or install["id"] not in mapping.get("install_profiles", [])
        ):
            raise ValueError(
                f"install profile {install['id']} is not enabled by its API/ABI mapping"
            )
    return levels, profiles, install_profiles


def render_make_api_levels(
    levels: list[dict[str, object]],
    profiles: list[dict[str, object]],
    install_profiles: list[dict[str, object]],
) -> str:
    names = [str(entry["api_level"]) for entry in levels]
    implemented = [
        str(entry["api_level"])
        for entry in levels
        if entry.get("catalog_status") == "implemented"
    ]
    pairs = [
        f"{level}/{profile['id']}"
        for profile in profiles
        for level, mapping in profile["api_level_mappings"].items()
        if mapping.get("target_build")
    ]
    triples = [
        f"{level}/{profile['id']}/{install_id}"
        for profile in profiles
        for level, mapping in profile["api_level_mappings"].items()
        if mapping.get("target_build")
        for install_id in mapping.get("install_profiles", [])
    ]
    lines = [
        "# Generated by tools/generate.py. Do not edit.",
        f"LIBWIPI_KNOWN_API_LEVELS := {' '.join(names)}",
        f"LIBWIPI_IMPLEMENTED_API_LEVELS := {' '.join(implemented)}",
        "LIBWIPI_KNOWN_PROFILES := "
        + " ".join(str(profile["id"]) for profile in profiles),
        "LIBWIPI_KNOWN_INSTALL_PROFILES := none "
        + " ".join(str(install["id"]) for install in install_profiles),
        f"LIBWIPI_AVAILABLE_API_PROFILE_PAIRS := {' '.join(pairs)}",
        f"LIBWIPI_AVAILABLE_BUILD_TRIPLES := {' '.join(triples)}",
        "",
    ]
    for level in implemented:
        lines.extend(
            [
                f"ifeq ($(API_LEVEL),{level})",
                f"WIPI_API_CPPFLAGS := -D{api_macro(level)}=1",
                "endif",
                "",
            ]
        )
    for install in install_profiles:
        macro = re.sub(r"[^0-9A-Za-z]+", "_", str(install["id"])).upper()
        lines.extend(
            [
                f"ifeq ($(INSTALL_PROFILE),{install['id']})",
                f"WIPI_INSTALL_CPPFLAGS := -DLIBWIPI_INSTALL_{macro}=1",
                "endif",
                "",
            ]
        )
    return "\n".join(lines)


def render_api_levels_header(levels: list[dict[str, object]]) -> str:
    implemented = [
        str(entry["api_level"])
        for entry in levels
        if entry.get("catalog_status") == "implemented"
    ]
    expression = " + ".join(f"defined({api_macro(level)})" for level in implemented)
    lines = [
        GENERATED_NOTICE.rstrip(),
        "#ifndef LIBWIPI_GENERATED_API_LEVELS_H",
        "#define LIBWIPI_GENERATED_API_LEVELS_H",
        "",
        f"#if ({expression}) != 1",
        '#error "select exactly one implemented libwipi API level"',
        "#endif",
        "",
    ]
    for index, level in enumerate(implemented):
        components = [int(component) for component in level.split(".")]
        components.extend([0] * (3 - len(components)))
        directive = "#if" if index == 0 else "#elif"
        lines.extend(
            [
                f"{directive} defined({api_macro(level)})",
                f'#define LIBWIPI_API_LEVEL "{level}"',
                f"#define LIBWIPI_API_VERSION_MAJOR {components[0]}",
                f"#define LIBWIPI_API_VERSION_MINOR {components[1]}",
                f"#define LIBWIPI_API_VERSION_PATCH {components[2]}",
            ]
        )
    lines.extend(["#endif", "", "#endif /* LIBWIPI_GENERATED_API_LEVELS_H */", ""])
    return "\n".join(lines)


def repository_path(relative: object, label: str) -> Path:
    if not isinstance(relative, str) or not relative:
        raise ValueError(f"{label} must be a non-empty repository path")
    path = (ROOT / relative).resolve()
    try:
        path.relative_to(ROOT.resolve())
    except ValueError as error:
        raise ValueError(f"{label} escapes the repository: {relative}") from error
    return path


def read_catalogs(
    levels: list[dict[str, object]],
) -> dict[str, list[dict[str, str]]]:
    catalogs: dict[str, list[dict[str, str]]] = {}
    for entry in levels:
        if entry.get("catalog_status") != "implemented":
            if entry.get("catalog") is not None or entry.get("api_docs") is not None:
                raise ValueError(
                    f"unimplemented API level {entry['api_level']} has catalog outputs"
                )
            continue
        api_level = str(entry["api_level"])
        catalog_path = repository_path(entry.get("catalog"), f"{api_level} catalog")
        with catalog_path.open("r", encoding="utf-8", newline="") as stream:
            rows = list(csv.DictReader(stream))
        validate_catalog(api_level, rows, entry.get("catalog_invariants"))
        catalogs[api_level] = rows
    if not catalogs:
        raise ValueError("version manifest has no implemented catalogs")
    return catalogs


def validate_catalog(
    api_level: str,
    rows: list[dict[str, str]],
    raw_invariants: object,
) -> None:
    if not isinstance(raw_invariants, dict):
        raise ValueError(f"{api_level} catalog has no invariants")
    required = {
        "public_rows",
        "ordinal_first",
        "ordinal_last",
        "family_count",
        "ktf_samsung_confirmed",
        "ktf_samsung_candidate",
        "candidate_family",
    }
    if set(raw_invariants) != required:
        raise ValueError(f"{api_level} catalog invariants have an invalid shape")
    expected_rows = raw_invariants["public_rows"]
    first = raw_invariants["ordinal_first"]
    last = raw_invariants["ordinal_last"]
    if not all(isinstance(value, int) for value in (expected_rows, first, last)):
        raise ValueError(f"{api_level} catalog count invariants must be integers")
    if len(rows) != expected_rows:
        raise ValueError(
            f"{api_level} catalog has {len(rows)} rows, expected {expected_rows}"
        )
    ordinals = [int(row["ordinal"]) for row in rows]
    if ordinals != list(range(first, last + 1)):
        raise ValueError(
            f"{api_level} catalog ordinals must be exactly {first}..{last} in order"
        )
    if len({row["name"] for row in rows}) != len(rows):
        raise ValueError(f"{api_level} catalog API names must be unique")
    families = Counter(row["family"] for row in rows)
    if len(families) != raw_invariants["family_count"]:
        raise ValueError(f"{api_level} catalog has an unexpected family count")
    confirmed = sum(
        row["ktf_samsung_confidence"] == "confirmed" for row in rows
    )
    candidates = [
        row for row in rows if row["ktf_samsung_confidence"] == "candidate"
    ]
    if (
        confirmed != raw_invariants["ktf_samsung_confirmed"]
        or len(candidates) != raw_invariants["ktf_samsung_candidate"]
    ):
        raise ValueError(f"{api_level} catalog evidence split is stale")
    candidate_family = raw_invariants["candidate_family"]
    if any(row["family"] != candidate_family for row in candidates):
        raise ValueError(
            f"{api_level} candidate selector is outside {candidate_family}"
        )
    for row in rows:
        expected_name = re.search(r"([A-Za-z_]\w*)\s*\(", row["prototype"])
        if not expected_name or expected_name.group(1) != row["name"]:
            raise ValueError(
                f"prototype/name mismatch for ordinal {row['ordinal']}: "
                f"{row['prototype']}"
            )


def prototype_parameter_names(prototype: str) -> set[str]:
    parameters = prototype[prototype.index("(") + 1 : prototype.rindex(")")]
    if parameters.strip() in {"", "void"}:
        return set()
    names: set[str] = set()
    for parameter in parameters.split(","):
        parameter = parameter.strip()
        if parameter == "...":
            continue
        match = re.search(r"([A-Za-z_]\w*)\s*(?:\[[^]]*\])?$", parameter)
        if not match:
            raise ValueError(f"cannot identify parameter in prototype: {prototype}")
        names.add(match.group(1))
    return names


def read_api_docs(
    level: dict[str, object], rows: list[dict[str, str]]
) -> dict[str, object]:
    def require_text(value: object, label: str) -> str:
        if not isinstance(value, str) or not value.strip():
            raise ValueError(f"{api_level} API docs {label} must be non-empty text")
        return value

    api_level = str(level["api_level"])
    path = repository_path(level.get("api_docs"), f"{api_level} API docs")
    document = json.loads(path.read_text(encoding="utf-8"))
    required = {
        "schema",
        "api_level",
        "reference_revision",
        "documentation_policy",
        "families",
        "symbols",
    }
    if set(document) != required or document.get("schema") != 1:
        raise ValueError(f"{api_level} API docs have an invalid top-level shape")
    if document.get("api_level") != api_level:
        raise ValueError(f"{api_level} API docs identify another API level")
    if document.get("reference_revision") != level.get("reference_revision"):
        raise ValueError(f"{api_level} API docs use an unpinned reference revision")
    require_text(document.get("documentation_policy"), "documentation policy")
    families = document.get("families")
    symbols = document.get("symbols")
    catalog_families = {row["family"] for row in rows}
    if not isinstance(families, dict) or set(families) != catalog_families:
        raise ValueError(f"{api_level} API docs do not cover every family")
    for family, documentation in families.items():
        if not isinstance(documentation, dict) or set(documentation) != {
            "title",
            "summary",
        }:
            raise ValueError(f"{api_level} API family docs are invalid: {family}")
        require_text(documentation["title"], f"{family} title")
        require_text(documentation["summary"], f"{family} summary")
    if not isinstance(symbols, dict):
        raise ValueError(f"{api_level} API docs symbols must be an object")
    by_name = {row["name"]: row for row in rows}
    unknown = set(symbols).difference(by_name)
    if unknown:
        raise ValueError(f"{api_level} API docs contain unknown symbols: {sorted(unknown)}")
    allowed = {
        "status",
        "summary",
        "details",
        "parameters",
        "returns",
        "ownership",
        "notes",
        "examples",
    }
    for name, documentation in symbols.items():
        if not isinstance(documentation, dict) or not {"status", "summary"}.issubset(
            documentation
        ):
            raise ValueError(f"{api_level} API docs entry is incomplete: {name}")
        if set(documentation).difference(allowed):
            raise ValueError(f"{api_level} API docs entry has unknown fields: {name}")
        if documentation["status"] not in {"draft", "reviewed"}:
            raise ValueError(f"{api_level} API docs status is invalid: {name}")
        require_text(documentation["summary"], f"{name} summary")
        for field in ("details", "returns", "ownership"):
            if field in documentation:
                require_text(documentation[field], f"{name} {field}")
        parameters = documentation.get("parameters", {})
        if not isinstance(parameters, dict):
            raise ValueError(f"{api_level} API docs parameters are invalid: {name}")
        for parameter, description in parameters.items():
            require_text(parameter, f"{name} parameter name")
            require_text(description, f"{name} parameter {parameter}")
        expected_parameters = prototype_parameter_names(by_name[name]["prototype"])
        if set(parameters) != expected_parameters:
            raise ValueError(
                f"{api_level} API docs parameter names do not match {name}: "
                f"expected {sorted(expected_parameters)}, got {sorted(parameters)}"
            )
        for field in ("notes", "examples"):
            values = documentation.get(field, [])
            if not isinstance(values, list) or len(values) != len(set(values)):
                raise ValueError(f"{api_level} API docs {field} are invalid: {name}")
            for index, value in enumerate(values):
                require_text(value, f"{name} {field}[{index}]")
    return document


def doxygen_comment(
    api_level: str, row: dict[str, str], documentation: dict[str, object] | None
) -> list[str]:
    def safe(value: object) -> str:
        return str(value).replace("*/", "* /")

    if documentation is None:
        summary = (
            f"Cataloged WIPI-C {api_level} API; detailed semantics are not yet reviewed."
        )
        status = "cataloged"
    else:
        summary = safe(documentation["summary"])
        status = safe(documentation["status"])
    lines = ["/**", f" * @brief {summary}"]
    if documentation is not None and documentation.get("details"):
        lines.append(f" * @details {safe(documentation['details'])}")
    if documentation is not None:
        for name, description in documentation.get("parameters", {}).items():
            lines.append(f" * @param {name} {safe(description)}")
        if documentation.get("returns"):
            lines.append(f" * @return {safe(documentation['returns'])}")
        if documentation.get("ownership"):
            lines.extend([" * @par Ownership", f" * {safe(documentation['ownership'])}"])
        for note in documentation.get("notes", []):
            lines.append(f" * @note {safe(note)}")
    lines.extend(
        [
            " * @par API level",
            f" * WIPI-C {api_level}, ordinal {int(row['ordinal'])}.",
            " * @par Documentation status",
            f" * {status}.",
            " */",
        ]
    )
    return lines


def render_family_header(
    api_level: str,
    family: str,
    rows: list[dict[str, str]],
    api_docs: dict[str, object],
) -> str:
    filename = FAMILY_FILES[family]
    guard = f"LIBWIPI_GENERATED_{filename.upper()}_H"
    lines = [
        GENERATED_NOTICE.rstrip(),
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <wipi/api_level.h>",
        "#include <wipi/abi_types.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    symbol_docs = api_docs["symbols"]
    for row in rows:
        lines.extend(doxygen_comment(api_level, row, symbol_docs.get(row["name"])))
        lines.append(f"{row['prototype']};")
    lines.extend(
        [
            "",
            "#ifdef __cplusplus",
            "}",
            "#endif",
            "",
            f"#endif /* {guard} */",
            "",
        ]
    )
    return "\n".join(lines)


def render_umbrella_header() -> str:
    lines = [
        GENERATED_NOTICE.rstrip(),
        "#ifndef LIBWIPI_GENERATED_API_H",
        "#define LIBWIPI_GENERATED_API_H",
        "",
        "#include <wipi/api_level.h>",
        "",
    ]
    for filename in FAMILY_FILES.values():
        lines.append(f"#include <wipi/generated/{filename}.h>")
    lines.extend(
        [
            "#include <string.h>",
            "#include <stdlib.h>",
            "#include <time.h>",
            "",
            "#endif /* LIBWIPI_GENERATED_API_H */",
            "",
        ]
    )
    return "\n".join(lines)


def render_counts_header(rows: list[dict[str, str]]) -> str:
    counts = Counter(row["family"] for row in rows)
    lines = [
        GENERATED_NOTICE.rstrip(),
        "#ifndef LIBWIPI_GENERATED_API_COUNTS_H",
        "#define LIBWIPI_GENERATED_API_COUNTS_H",
        "",
        "#include <wipi/api_level.h>",
        "",
        f"#define LIBWIPI_PUBLIC_API_COUNT {len(rows)}",
        "#define LIBWIPI_CONFIRMED_KTF_SAMSUNG_SELECTOR_COUNT "
        + str(sum(row["ktf_samsung_confidence"] == "confirmed" for row in rows)),
        "#define LIBWIPI_CANDIDATE_KTF_SAMSUNG_SELECTOR_COUNT "
        + str(sum(row["ktf_samsung_confidence"] == "candidate" for row in rows)),
    ]
    for family in sorted(counts):
        macro = re.sub(r"[^A-Z0-9]+", "_", family.upper())
        lines.append(f"#define LIBWIPI_{macro}_API_COUNT {counts[family]}")
    lines.extend(["", "#endif /* LIBWIPI_GENERATED_API_COUNTS_H */", ""])
    return "\n".join(lines)


def table_symbol(family: str) -> str:
    return f"__wipi_ktf_table_{family.lower()}"


def render_resolve_and_tail(row: dict[str, str], special_timer: bool) -> list[str]:
    slot = int(row["ktf_samsung_slot"][1:], 16)
    lines: list[str] = []
    if special_timer:
        lines.extend(
            [
                "    @ AAPCS entry: r0=tm, r2:r3=timeout, [sp]=parm.",
                "    @ Samsung/KTF provider: r0=tm, r1:r2=timeout, r3=parm.",
                "    movs r1, r2",
                "    movs r2, r3",
                "    ldr r3, [sp]",
            ]
        )
    lines.extend(
        [
            "    push {r0}",
            f"    ldr r0, ={table_symbol(row['family'])}",
            "    ldr r0, [r0]",
            "    cmp r0, #0",
            "    beq 1f",
        ]
    )
    if slot:
        lines.append(f"    adds r0, #{slot}")
    lines.extend(
        [
            "    ldr r0, [r0]",
            "    cmp r0, #0",
            "    beq 1f",
            "    mov ip, r0",
            "    pop {r0}",
            "    bx ip",
            "1:",
            "    pop {r0}",
            "    ldr r0, =__wipi_missing_import",
            "    bx r0",
        ]
    )
    return lines


def render_ktf_veneer(rows: list[dict[str, str]]) -> str:
    eligible = [
        row
        for row in rows
        if row["implementation"] == "ktf-table"
        and row["ktf_samsung_confidence"] == "confirmed"
        and row["abi_class"] != "variadic-unverified"
    ]
    lines = [
        "/* Generated by tools/generate.py. Do not edit. */",
        ".syntax unified",
        ".cpu arm7tdmi",
        ".thumb",
        "",
    ]
    for row in eligible:
        name = row["name"]
        lines.extend(
            [
                f'.section .text.{name}, "ax", %progbits',
                ".align 1",
                f".global {name}",
                f".type {name}, %function",
                ".thumb_func",
                f"{name}:",
            ]
        )
        lines.extend(render_resolve_and_tail(row, name == "MC_knlSetTimer"))
        lines.extend([f".size {name}, .-{name}", ".pool", ""])
    return "\n".join(lines)


def render_thumb_u16(reg: str, value: int) -> list[str]:
    if value < 0 or value > 0xFFFF:
        raise ValueError(f"Thumb import immediate is out of range: {value:#x}")
    if value <= 0xFF:
        return [f"    movs {reg}, #{value:#x}"]
    lines = [
        f"    movs {reg}, #{value >> 8:#x}",
        f"    lsls {reg}, {reg}, #8",
    ]
    if value & 0xFF:
        lines.append(f"    adds {reg}, #{value & 0xFF:#x}")
    return lines


def render_lgt_resolve_and_tail(
    method: int,
    special_timer: bool,
    aram_method: int | None,
    wie_return_override: tuple[int, int] | None,
) -> list[str]:
    lines = [
        "    @ Preserve every argument word and the caller return address.",
        "    push {r0-r4, lr}",
    ]
    lines.extend(render_thumb_u16("r0", 0x1FB))
    if aram_method is None:
        lines.extend(render_thumb_u16("r1", method))
    else:
        lines.extend(
            [
                "    ldr r2, =__wipi_lgt_environment",
                "    ldr r2, [r2]",
                "    cmp r2, #1",
                "    bne 4f",
            ]
        )
        lines.extend(render_thumb_u16("r1", aram_method))
        lines.append("    b 5f")
        lines.append("4:")
        lines.extend(render_thumb_u16("r1", method))
        lines.append("5:")
    lines.extend(
        [
            "    ldr r3, =__wipi_lgt_resolver",
            "    ldr r3, [r3]",
            "    cmp r3, #0",
            "    beq 1f",
            "    ldr r3, [r3, #4]",
            "    cmp r3, #0",
            "    beq 1f",
            "    bl 3f",
            "    cmp r0, #0",
            "    beq 1f",
            "    mov ip, r0",
            "    b 2f",
            "1:",
            "    ldr r3, =__wipi_missing_import",
            "    mov ip, r3",
            "2:",
        ]
    )
    if wie_return_override is None:
        lines.extend(
            [
                "    ldr r4, [sp, #20]",
                "    mov lr, r4",
                "    pop {r0-r4}",
                "    add sp, #4",
            ]
        )
        if special_timer:
            lines.extend(
                [
                    "    @ AAPCS entry: r0=tm, r2:r3=timeout, [sp]=parm.",
                    "    @ LGT provider: r0=tm, r1:r2=timeout, r3=parm.",
                    "    movs r1, r2",
                    "    movs r2, r3",
                    "    ldr r3, [sp]",
                ]
            )
        lines.append("    bx ip")
    else:
        if special_timer:
            raise ValueError("MC_knlSetTimer cannot use a return override")
        provider_success, public_success = wie_return_override
        lines.extend(
            [
                "    @ Preserve the provider address across the real call.",
                "    mov r4, ip",
                "    pop {r0-r3}",
                "    bl 6f",
                f"    @ WIE provider success {provider_success} maps to public WIPI success {public_success}.",
                "    ldr r2, =__wipi_lgt_environment",
                "    ldr r2, [r2]",
                "    cmp r2, #2",
                "    bne 7f",
                f"    cmp r0, #{provider_success}",
                "    bne 7f",
                f"    movs r0, #{public_success}",
                "7:",
                "    pop {r4}",
                "    pop {r1}",
                "    bx r1",
                "6:",
                "    @ ARMv4T provider-call thunk (BLX is ARMv5T).",
                "    bx r4",
            ]
        )
    lines.extend(
        [
            "3:",
            "    @ ARMv4T Thumb resolver-call thunk (BLX is ARMv5T).",
            "    bx r3",
        ]
    )
    return lines


def render_lgt_veneer(
    rows: list[dict[str, str]], install: dict[str, object]
) -> str:
    imports = install.get("imports")
    if not isinstance(imports, dict):
        raise ValueError(f"install profile {install['id']} has no imports")
    if imports.get("default_environment") != "wie":
        raise ValueError(
            f"install profile {install['id']} must identify the default method map"
        )
    methods = imports.get("confirmed_public_methods")
    if not isinstance(methods, dict) or not methods:
        raise ValueError(f"install profile {install['id']} has no public methods")
    by_name = {row["name"]: row for row in rows}
    unknown = set(methods).difference(by_name)
    if unknown:
        raise ValueError(f"LGT methods are absent from the catalog: {sorted(unknown)}")

    overrides = imports.get("aram_method_overrides", {})
    if not isinstance(overrides, dict) or not set(overrides).issubset(methods):
        raise ValueError(f"install profile {install['id']} has invalid ARAM overrides")

    return_overrides = imports.get("return_overrides", {})
    if not isinstance(return_overrides, dict) or not set(return_overrides).issubset(
        methods
    ):
        raise ValueError(f"install profile {install['id']} has invalid return overrides")
    parsed_return_overrides: dict[str, tuple[int, int]] = {}
    for name, override in return_overrides.items():
        if not isinstance(override, dict) or set(override) != {
            "environment",
            "provider_success",
            "public_success",
        }:
            raise ValueError(f"LGT return override has an invalid shape: {name}")
        if override["environment"] != "wie":
            raise ValueError(f"unsupported LGT return-override environment: {name}")
        provider_success = override["provider_success"]
        public_success = override["public_success"]
        if not isinstance(provider_success, int) or not 0 <= provider_success <= 0xFF:
            raise ValueError(f"LGT provider success is not a Thumb immediate: {name}")
        if not isinstance(public_success, int) or not 0 <= public_success <= 0xFF:
            raise ValueError(f"LGT public success is not a Thumb immediate: {name}")
        parsed_return_overrides[name] = (provider_success, public_success)

    eligible: list[
        tuple[dict[str, str], int, int | None, tuple[int, int] | None]
    ] = []
    for name, encoded_method in methods.items():
        row = by_name[name]
        if row["abi_class"] == "variadic-unverified":
            raise ValueError(f"variadic LGT method cannot generate a veneer: {name}")
        method = int(str(encoded_method), 0)
        aram_method = (
            int(str(overrides[name]), 0) if name in overrides else None
        )
        eligible.append(
            (row, method, aram_method, parsed_return_overrides.get(name))
        )

    lines = [
        "/* Generated by tools/generate.py. Do not edit. */",
        ".syntax unified",
        ".cpu arm7tdmi",
        ".thumb",
        "",
    ]
    for row, method, aram_method, wie_return_override in eligible:
        name = row["name"]
        lines.extend(
            [
                f'.section .text.{name}, "ax", %progbits',
                ".align 1",
                f".global {name}",
                f".type {name}, %function",
                ".thumb_func",
                f"{name}:",
            ]
        )
        lines.extend(
            render_lgt_resolve_and_tail(
                method,
                name == "MC_knlSetTimer",
                aram_method,
                wie_return_override,
            )
        )
        lines.extend([f".size {name}, .-{name}", ".pool", ""])
    return "\n".join(lines)


def render_coverage(api_level: str, rows: list[dict[str, str]]) -> str:
    counts = Counter(row["family"] for row in rows)
    candidates = [
        row for row in rows if row["ktf_samsung_confidence"] == "candidate"
    ]
    variadic = [row for row in rows if row["abi_class"] == "variadic-unverified"]
    veneer_count = sum(
        row["implementation"] == "ktf-table"
        and row["ktf_samsung_confidence"] == "confirmed"
        and row["abi_class"] != "variadic-unverified"
        for row in rows
    )
    lines = [
        "<!-- Generated by tools/generate.py. Do not edit. -->",
        f"# WIPI {api_level} API coverage",
        "",
        f"- Public API rows: **{len(rows)}**",
        "- Samsung/KTF confirmed selectors: "
        f"**{sum(row['ktf_samsung_confidence'] == 'confirmed' for row in rows)}**",
        "- Samsung/KTF candidate selectors: "
        f"**{sum(row['ktf_samsung_confidence'] == 'candidate' for row in rows)}**",
        f"- Generated Samsung/KTF tail veneers: **{veneer_count}**",
        "- CSTDLIB strategy: **local freestanding implementation**",
        "",
        "## Families",
        "",
        "| Family | APIs |",
        "|---|---:|",
    ]
    for family in sorted(counts):
        lines.append(f"| `{family}` | {counts[family]} |")
    lines.extend(["", "## Candidate selectors not called by libwipi", ""])
    for row in candidates:
        lines.append(f"- `{row['name']}` ({row['ktf_samsung_slot']})")
    lines.extend(["", "## Variadic APIs requiring explicit wrappers", ""])
    for row in variadic:
        lines.append(f"- `{row['name']}`")
    lines.append("")
    return "\n".join(lines)


def generated_files(
    api_level: str,
    rows: list[dict[str, str]],
    api_docs: dict[str, object],
    levels: list[dict[str, object]],
    profiles: list[dict[str, object]],
    install_profiles: list[dict[str, object]],
) -> dict[Path, str]:
    result: dict[Path, str] = {}
    for family, filename in FAMILY_FILES.items():
        family_rows = [row for row in rows if row["family"] == family]
        result[ROOT / "include" / "wipi" / "generated" / f"{filename}.h"] = (
            render_family_header(api_level, family, family_rows, api_docs)
        )
    result[ROOT / "include" / "wipi" / "generated" / "api.h"] = (
        render_umbrella_header()
    )
    result[ROOT / "include" / "wipi" / "generated" / "api_counts.h"] = (
        render_counts_header(rows)
    )
    result[ROOT / "include" / "wipi" / "generated" / "api_levels.h"] = (
        render_api_levels_header(levels)
    )
    result[ROOT / "mk" / "generated" / "api-levels.mk"] = (
        render_make_api_levels(levels, profiles, install_profiles)
    )
    result[ROOT / "src" / "abi" / "ktf" / "generated_veneer.S"] = (
        render_ktf_veneer(rows)
    )
    for install in install_profiles:
        if install["abi_profile"] != "lgt-raptor":
            continue
        install_id = str(install["id"])
        filename = (
            "generated_veneer.S"
            if install_id == "aram-wie-raptor"
            else "generated_veneer_" + install_id.replace("-", "_") + ".S"
        )
        result[ROOT / "src" / "abi" / "lgt" / filename] = render_lgt_veneer(
            rows, install
        )
    result[ROOT / "docs" / "generated" / "api-coverage.md"] = render_coverage(
        api_level, rows
    )
    return result


def update_files(files: dict[Path, str], check: bool) -> int:
    stale: list[Path] = []
    for path, content in files.items():
        normalized = content.replace("\r\n", "\n")
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == normalized:
            continue
        stale.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(normalized, encoding="utf-8", newline="\n")
    if stale:
        verb = "stale" if check else "generated"
        for path in stale:
            print(f"{verb}: {path.relative_to(ROOT)}")
    if check and stale:
        return 1
    if check:
        print(f"generated files are current ({len(files)} files)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        manifest, manifest_levels = read_version_manifest()
        levels, profiles, install_profiles = read_build_metadata()
        catalogs = read_catalogs(manifest_levels)
        api_level = str(manifest["bootstrap_api_level"])
        rows = catalogs[api_level]
        level = next(entry for entry in levels if entry["api_level"] == api_level)
        api_docs = read_api_docs(level, rows)
        return update_files(
            generated_files(
                api_level,
                rows,
                api_docs,
                levels,
                profiles,
                install_profiles,
            ),
            args.check,
        )
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
