LIBWIPI_ROOT ?= ../..

API_LEVEL ?= 1.2.1
PROFILE ?= ktf-samsung
INSTALL_PROFILE ?= sch-w8300-qpst-probe

APP_AID := libwipi-sch-w8300-probe
APP_NAME := libwipi SCH-W8300 probe
APP_SOURCES := main.c

include $(LIBWIPI_ROOT)/mk/application.mk
